#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && cd .. && pwd )"

sudo chmod 664 `find ${DIR} -type f | grep -v 'vendor' | grep -v '.git' | grep -v scripts`
sudo chmod 775 `find ${DIR} -type d | grep -v 'vendor' | grep -v '.git'`
sudo chown -R will:www ${DIR}/*
